### ISSUE TITLE
Offset arrays

### ISSUE THREAD

**Issue by ali-ramadhan** [natgeo-wong/GillMatsuno.jl#1]
Looks like the perfect place to use [OffsetArrays.jl](https://github.com/JuliaArrays/OffsetArrays.jl) haha.

But otherwise cool repository!

https://github.com/natgeo-wong/GillMatsuno.jl/blob/44ed54b7df1f4c989b38989c773ba2082328e126/src/numwaves.jl#L41-L60

**Comment by natgeo-wong** [comment]
Thank you for the suggestion!!!
It's very much a WIP/messy stage at this moment I think I'm going to clean it up over the next week or so and write the numerical solver for the actual GM solutions.

**Comment by natgeo-wong** [comment]
I used circshift() instead because it felt more appropriate haha.  I'll have a look at OffsetArrays.jl later when I actually understand that package.  I got lost looking through the docs.

**Comment by ali-ramadhan** [comment]
Ah nice! Yeah OffsetArrays.jl is very nice if you use ghost points (halo regions, or whatever they're called) as you can assign indices 0, -1, -2, ... and N+1, N+2, ... to the ghost points. But if you're just doing derivatives then yeah they don't buy you anything.
